version: '3.3'

services:
  postgres:
    image: 'postgres:14'
    environment:
      - POSTGRES_DB=platzi_store_nestjs
      - POSTGRES_USER=felipe
      - POSTGRES_PASSWORD=123456
    ports:
      - '5432:5432'
    volumes:
      - ./postgres_data:/var/lib/postgresql/data